// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChyNd-kZtRo6rYugs5fA56xYF4eqngqms',
    appId: '1:751405322678:web:303200daee0d046206b117',
    messagingSenderId: '751405322678',
    projectId: 'catalogo-ropa-app',
    authDomain: 'catalogo-ropa-app.firebaseapp.com',
    storageBucket: 'catalogo-ropa-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL3eaNSPyC0bkZsUEYe61ybTjbYGe8vYE',
    appId: '1:751405322678:android:8d628ef5832344fe06b117',
    messagingSenderId: '751405322678',
    projectId: 'catalogo-ropa-app',
    storageBucket: 'catalogo-ropa-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbxooKz6P4OJM46RL4GgDoKNDW7oZS_tg',
    appId: '1:751405322678:ios:1025f3b9a66d6b7906b117',
    messagingSenderId: '751405322678',
    projectId: 'catalogo-ropa-app',
    storageBucket: 'catalogo-ropa-app.appspot.com',
    iosClientId: '751405322678-eneik82koajp8h8kgs17i5dmr3fk007o.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectCatalogo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbxooKz6P4OJM46RL4GgDoKNDW7oZS_tg',
    appId: '1:751405322678:ios:1025f3b9a66d6b7906b117',
    messagingSenderId: '751405322678',
    projectId: 'catalogo-ropa-app',
    storageBucket: 'catalogo-ropa-app.appspot.com',
    iosClientId: '751405322678-eneik82koajp8h8kgs17i5dmr3fk007o.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectCatalogo',
  );
}
